import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  ISO8601DateTime: { input: any; output: any; }
};

export type Chatroom = {
  __typename?: 'Chatroom';
  callerPhoneNumber: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  label: Scalars['String']['output'];
  natureCode?: Maybe<NatureCode>;
  resolved: Scalars['Boolean']['output'];
};

export type ChatroomNote = {
  __typename?: 'ChatroomNote';
  chatroom: Chatroom;
  content: Scalars['String']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
};

/** Autogenerated input type of CreateChatroom */
export type CreateChatroomInput = {
  callerPhoneNumber: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  label: Scalars['String']['input'];
  natureCodeId?: InputMaybe<Scalars['ID']['input']>;
};

/** Autogenerated input type of CreateChatroomNote */
export type CreateChatroomNoteInput = {
  chatroomId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  content: Scalars['String']['input'];
};

/** Autogenerated return type of CreateChatroomNote. */
export type CreateChatroomNotePayload = {
  __typename?: 'CreateChatroomNotePayload';
  chatroomNote: ChatroomNote;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated return type of CreateChatroom. */
export type CreateChatroomPayload = {
  __typename?: 'CreateChatroomPayload';
  chatroom: Chatroom;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

export type Mutation = {
  __typename?: 'Mutation';
  createChatroom?: Maybe<CreateChatroomPayload>;
  createChatroomNote?: Maybe<CreateChatroomNotePayload>;
  toggleChatroomResolved?: Maybe<ToggleChatroomResolvedPayload>;
  updateChatroomDescription?: Maybe<UpdateChatroomDescriptionPayload>;
};


export type MutationCreateChatroomArgs = {
  input: CreateChatroomInput;
};


export type MutationCreateChatroomNoteArgs = {
  input: CreateChatroomNoteInput;
};


export type MutationToggleChatroomResolvedArgs = {
  input: ToggleChatroomResolvedInput;
};


export type MutationUpdateChatroomDescriptionArgs = {
  input: UpdateChatroomDescriptionInput;
};

export type NatureCode = {
  __typename?: 'NatureCode';
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
};

export type Query = {
  __typename?: 'Query';
  chatroomNotes: Array<ChatroomNote>;
  chatrooms: Array<Chatroom>;
  natureCodes: Array<NatureCode>;
};


export type QueryChatroomNotesArgs = {
  chatroomId: Scalars['ID']['input'];
};


export type QueryChatroomsArgs = {
  resolved?: InputMaybe<Scalars['Boolean']['input']>;
};

/** Autogenerated input type of ToggleChatroomResolved */
export type ToggleChatroomResolvedInput = {
  chatroomId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  resolved: Scalars['Boolean']['input'];
};

/** Autogenerated return type of ToggleChatroomResolved. */
export type ToggleChatroomResolvedPayload = {
  __typename?: 'ToggleChatroomResolvedPayload';
  chatroom: Chatroom;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of UpdateChatroomDescription */
export type UpdateChatroomDescriptionInput = {
  chatroomId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  newDescription?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UpdateChatroomDescription. */
export type UpdateChatroomDescriptionPayload = {
  __typename?: 'UpdateChatroomDescriptionPayload';
  chatroom: Chatroom;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

export type ChatroomDataFragment = { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null };

export type ChatroomNoteDataFragment = { __typename?: 'ChatroomNote', id: string, content: string, createdAt: any, chatroom: { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null } };

export type NatureCodeDataFragment = { __typename?: 'NatureCode', id: string, name: string };

export type CreateChatroomMutationVariables = Exact<{
  label: Scalars['String']['input'];
  callerPhoneNumber: Scalars['String']['input'];
  description?: InputMaybe<Scalars['String']['input']>;
  natureCodeId?: InputMaybe<Scalars['ID']['input']>;
}>;


export type CreateChatroomMutation = { __typename?: 'Mutation', createChatroom?: { __typename?: 'CreateChatroomPayload', chatroom: { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null } } | null };

export type CreateChatroomNoteMutationVariables = Exact<{
  chatroomId: Scalars['ID']['input'];
  content: Scalars['String']['input'];
}>;


export type CreateChatroomNoteMutation = { __typename?: 'Mutation', createChatroomNote?: { __typename?: 'CreateChatroomNotePayload', chatroomNote: { __typename?: 'ChatroomNote', id: string, content: string, createdAt: any, chatroom: { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null } } } | null };

export type ToggleChatroomResolvedMutationVariables = Exact<{
  chatroomId: Scalars['ID']['input'];
  resolved: Scalars['Boolean']['input'];
}>;


export type ToggleChatroomResolvedMutation = { __typename?: 'Mutation', toggleChatroomResolved?: { __typename?: 'ToggleChatroomResolvedPayload', chatroom: { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null } } | null };

export type UpdateChatroomDescriptionMutationVariables = Exact<{
  chatroomId: Scalars['ID']['input'];
  newDescription?: InputMaybe<Scalars['String']['input']>;
}>;


export type UpdateChatroomDescriptionMutation = { __typename?: 'Mutation', updateChatroomDescription?: { __typename?: 'UpdateChatroomDescriptionPayload', chatroom: { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null } } | null };

export type ArchivedChatroomsListQueryVariables = Exact<{ [key: string]: never; }>;


export type ArchivedChatroomsListQuery = { __typename?: 'Query', chatrooms: Array<{ __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null }> };

export type ChatroomNotesQueryVariables = Exact<{
  chatroomId: Scalars['ID']['input'];
}>;


export type ChatroomNotesQuery = { __typename?: 'Query', chatroomNotes: Array<{ __typename?: 'ChatroomNote', id: string, content: string, createdAt: any, chatroom: { __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null } }> };

export type ChatroomsListQueryVariables = Exact<{ [key: string]: never; }>;


export type ChatroomsListQuery = { __typename?: 'Query', chatrooms: Array<{ __typename?: 'Chatroom', id: string, label: string, description?: string | null, callerPhoneNumber: string, resolved: boolean, natureCode?: { __typename?: 'NatureCode', id: string, name: string } | null }> };

export type NatureCodesQueryVariables = Exact<{ [key: string]: never; }>;


export type NatureCodesQuery = { __typename?: 'Query', natureCodes: Array<{ __typename?: 'NatureCode', id: string, name: string }> };

export const NatureCodeDataFragmentDoc = gql`
    fragment NatureCodeData on NatureCode {
  id
  name
}
    `;
export const ChatroomDataFragmentDoc = gql`
    fragment ChatroomData on Chatroom {
  id
  label
  description
  callerPhoneNumber
  resolved
  natureCode {
    ...NatureCodeData
  }
}
    ${NatureCodeDataFragmentDoc}`;
export const ChatroomNoteDataFragmentDoc = gql`
    fragment ChatroomNoteData on ChatroomNote {
  id
  content
  chatroom {
    ...ChatroomData
  }
  createdAt
}
    ${ChatroomDataFragmentDoc}`;
export const CreateChatroomDocument = gql`
    mutation CreateChatroom($label: String!, $callerPhoneNumber: String!, $description: String, $natureCodeId: ID) {
  createChatroom(
    input: {label: $label, callerPhoneNumber: $callerPhoneNumber, description: $description, natureCodeId: $natureCodeId}
  ) {
    chatroom {
      ...ChatroomData
    }
  }
}
    ${ChatroomDataFragmentDoc}`;
export type CreateChatroomMutationFn = Apollo.MutationFunction<CreateChatroomMutation, CreateChatroomMutationVariables>;

/**
 * __useCreateChatroomMutation__
 *
 * To run a mutation, you first call `useCreateChatroomMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateChatroomMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createChatroomMutation, { data, loading, error }] = useCreateChatroomMutation({
 *   variables: {
 *      label: // value for 'label'
 *      callerPhoneNumber: // value for 'callerPhoneNumber'
 *      description: // value for 'description'
 *      natureCodeId: // value for 'natureCodeId'
 *   },
 * });
 */
export function useCreateChatroomMutation(baseOptions?: Apollo.MutationHookOptions<CreateChatroomMutation, CreateChatroomMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateChatroomMutation, CreateChatroomMutationVariables>(CreateChatroomDocument, options);
      }
export type CreateChatroomMutationHookResult = ReturnType<typeof useCreateChatroomMutation>;
export type CreateChatroomMutationResult = Apollo.MutationResult<CreateChatroomMutation>;
export type CreateChatroomMutationOptions = Apollo.BaseMutationOptions<CreateChatroomMutation, CreateChatroomMutationVariables>;
export const CreateChatroomNoteDocument = gql`
    mutation CreateChatroomNote($chatroomId: ID!, $content: String!) {
  createChatroomNote(input: {chatroomId: $chatroomId, content: $content}) {
    chatroomNote {
      ...ChatroomNoteData
    }
  }
}
    ${ChatroomNoteDataFragmentDoc}`;
export type CreateChatroomNoteMutationFn = Apollo.MutationFunction<CreateChatroomNoteMutation, CreateChatroomNoteMutationVariables>;

/**
 * __useCreateChatroomNoteMutation__
 *
 * To run a mutation, you first call `useCreateChatroomNoteMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateChatroomNoteMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createChatroomNoteMutation, { data, loading, error }] = useCreateChatroomNoteMutation({
 *   variables: {
 *      chatroomId: // value for 'chatroomId'
 *      content: // value for 'content'
 *   },
 * });
 */
export function useCreateChatroomNoteMutation(baseOptions?: Apollo.MutationHookOptions<CreateChatroomNoteMutation, CreateChatroomNoteMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateChatroomNoteMutation, CreateChatroomNoteMutationVariables>(CreateChatroomNoteDocument, options);
      }
export type CreateChatroomNoteMutationHookResult = ReturnType<typeof useCreateChatroomNoteMutation>;
export type CreateChatroomNoteMutationResult = Apollo.MutationResult<CreateChatroomNoteMutation>;
export type CreateChatroomNoteMutationOptions = Apollo.BaseMutationOptions<CreateChatroomNoteMutation, CreateChatroomNoteMutationVariables>;
export const ToggleChatroomResolvedDocument = gql`
    mutation ToggleChatroomResolved($chatroomId: ID!, $resolved: Boolean!) {
  toggleChatroomResolved(input: {chatroomId: $chatroomId, resolved: $resolved}) {
    chatroom {
      ...ChatroomData
    }
  }
}
    ${ChatroomDataFragmentDoc}`;
export type ToggleChatroomResolvedMutationFn = Apollo.MutationFunction<ToggleChatroomResolvedMutation, ToggleChatroomResolvedMutationVariables>;

/**
 * __useToggleChatroomResolvedMutation__
 *
 * To run a mutation, you first call `useToggleChatroomResolvedMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useToggleChatroomResolvedMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [toggleChatroomResolvedMutation, { data, loading, error }] = useToggleChatroomResolvedMutation({
 *   variables: {
 *      chatroomId: // value for 'chatroomId'
 *      resolved: // value for 'resolved'
 *   },
 * });
 */
export function useToggleChatroomResolvedMutation(baseOptions?: Apollo.MutationHookOptions<ToggleChatroomResolvedMutation, ToggleChatroomResolvedMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ToggleChatroomResolvedMutation, ToggleChatroomResolvedMutationVariables>(ToggleChatroomResolvedDocument, options);
      }
export type ToggleChatroomResolvedMutationHookResult = ReturnType<typeof useToggleChatroomResolvedMutation>;
export type ToggleChatroomResolvedMutationResult = Apollo.MutationResult<ToggleChatroomResolvedMutation>;
export type ToggleChatroomResolvedMutationOptions = Apollo.BaseMutationOptions<ToggleChatroomResolvedMutation, ToggleChatroomResolvedMutationVariables>;
export const UpdateChatroomDescriptionDocument = gql`
    mutation UpdateChatroomDescription($chatroomId: ID!, $newDescription: String) {
  updateChatroomDescription(
    input: {chatroomId: $chatroomId, newDescription: $newDescription}
  ) {
    chatroom {
      ...ChatroomData
    }
  }
}
    ${ChatroomDataFragmentDoc}`;
export type UpdateChatroomDescriptionMutationFn = Apollo.MutationFunction<UpdateChatroomDescriptionMutation, UpdateChatroomDescriptionMutationVariables>;

/**
 * __useUpdateChatroomDescriptionMutation__
 *
 * To run a mutation, you first call `useUpdateChatroomDescriptionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateChatroomDescriptionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateChatroomDescriptionMutation, { data, loading, error }] = useUpdateChatroomDescriptionMutation({
 *   variables: {
 *      chatroomId: // value for 'chatroomId'
 *      newDescription: // value for 'newDescription'
 *   },
 * });
 */
export function useUpdateChatroomDescriptionMutation(baseOptions?: Apollo.MutationHookOptions<UpdateChatroomDescriptionMutation, UpdateChatroomDescriptionMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdateChatroomDescriptionMutation, UpdateChatroomDescriptionMutationVariables>(UpdateChatroomDescriptionDocument, options);
      }
export type UpdateChatroomDescriptionMutationHookResult = ReturnType<typeof useUpdateChatroomDescriptionMutation>;
export type UpdateChatroomDescriptionMutationResult = Apollo.MutationResult<UpdateChatroomDescriptionMutation>;
export type UpdateChatroomDescriptionMutationOptions = Apollo.BaseMutationOptions<UpdateChatroomDescriptionMutation, UpdateChatroomDescriptionMutationVariables>;
export const ArchivedChatroomsListDocument = gql`
    query ArchivedChatroomsList {
  chatrooms(resolved: true) {
    ...ChatroomData
  }
}
    ${ChatroomDataFragmentDoc}`;

/**
 * __useArchivedChatroomsListQuery__
 *
 * To run a query within a React component, call `useArchivedChatroomsListQuery` and pass it any options that fit your needs.
 * When your component renders, `useArchivedChatroomsListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useArchivedChatroomsListQuery({
 *   variables: {
 *   },
 * });
 */
export function useArchivedChatroomsListQuery(baseOptions?: Apollo.QueryHookOptions<ArchivedChatroomsListQuery, ArchivedChatroomsListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ArchivedChatroomsListQuery, ArchivedChatroomsListQueryVariables>(ArchivedChatroomsListDocument, options);
      }
export function useArchivedChatroomsListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ArchivedChatroomsListQuery, ArchivedChatroomsListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ArchivedChatroomsListQuery, ArchivedChatroomsListQueryVariables>(ArchivedChatroomsListDocument, options);
        }
export type ArchivedChatroomsListQueryHookResult = ReturnType<typeof useArchivedChatroomsListQuery>;
export type ArchivedChatroomsListLazyQueryHookResult = ReturnType<typeof useArchivedChatroomsListLazyQuery>;
export type ArchivedChatroomsListQueryResult = Apollo.QueryResult<ArchivedChatroomsListQuery, ArchivedChatroomsListQueryVariables>;
export const ChatroomNotesDocument = gql`
    query ChatroomNotes($chatroomId: ID!) {
  chatroomNotes(chatroomId: $chatroomId) {
    ...ChatroomNoteData
  }
}
    ${ChatroomNoteDataFragmentDoc}`;

/**
 * __useChatroomNotesQuery__
 *
 * To run a query within a React component, call `useChatroomNotesQuery` and pass it any options that fit your needs.
 * When your component renders, `useChatroomNotesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useChatroomNotesQuery({
 *   variables: {
 *      chatroomId: // value for 'chatroomId'
 *   },
 * });
 */
export function useChatroomNotesQuery(baseOptions: Apollo.QueryHookOptions<ChatroomNotesQuery, ChatroomNotesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ChatroomNotesQuery, ChatroomNotesQueryVariables>(ChatroomNotesDocument, options);
      }
export function useChatroomNotesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ChatroomNotesQuery, ChatroomNotesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ChatroomNotesQuery, ChatroomNotesQueryVariables>(ChatroomNotesDocument, options);
        }
export type ChatroomNotesQueryHookResult = ReturnType<typeof useChatroomNotesQuery>;
export type ChatroomNotesLazyQueryHookResult = ReturnType<typeof useChatroomNotesLazyQuery>;
export type ChatroomNotesQueryResult = Apollo.QueryResult<ChatroomNotesQuery, ChatroomNotesQueryVariables>;
export const ChatroomsListDocument = gql`
    query ChatroomsList {
  chatrooms {
    ...ChatroomData
  }
}
    ${ChatroomDataFragmentDoc}`;

/**
 * __useChatroomsListQuery__
 *
 * To run a query within a React component, call `useChatroomsListQuery` and pass it any options that fit your needs.
 * When your component renders, `useChatroomsListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useChatroomsListQuery({
 *   variables: {
 *   },
 * });
 */
export function useChatroomsListQuery(baseOptions?: Apollo.QueryHookOptions<ChatroomsListQuery, ChatroomsListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ChatroomsListQuery, ChatroomsListQueryVariables>(ChatroomsListDocument, options);
      }
export function useChatroomsListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ChatroomsListQuery, ChatroomsListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ChatroomsListQuery, ChatroomsListQueryVariables>(ChatroomsListDocument, options);
        }
export type ChatroomsListQueryHookResult = ReturnType<typeof useChatroomsListQuery>;
export type ChatroomsListLazyQueryHookResult = ReturnType<typeof useChatroomsListLazyQuery>;
export type ChatroomsListQueryResult = Apollo.QueryResult<ChatroomsListQuery, ChatroomsListQueryVariables>;
export const NatureCodesDocument = gql`
    query NatureCodes {
  natureCodes {
    id
    name
  }
}
    `;

/**
 * __useNatureCodesQuery__
 *
 * To run a query within a React component, call `useNatureCodesQuery` and pass it any options that fit your needs.
 * When your component renders, `useNatureCodesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useNatureCodesQuery({
 *   variables: {
 *   },
 * });
 */
export function useNatureCodesQuery(baseOptions?: Apollo.QueryHookOptions<NatureCodesQuery, NatureCodesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<NatureCodesQuery, NatureCodesQueryVariables>(NatureCodesDocument, options);
      }
export function useNatureCodesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<NatureCodesQuery, NatureCodesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<NatureCodesQuery, NatureCodesQueryVariables>(NatureCodesDocument, options);
        }
export type NatureCodesQueryHookResult = ReturnType<typeof useNatureCodesQuery>;
export type NatureCodesLazyQueryHookResult = ReturnType<typeof useNatureCodesLazyQuery>;
export type NatureCodesQueryResult = Apollo.QueryResult<NatureCodesQuery, NatureCodesQueryVariables>;